output-format: json

strictness: medium
test-warnings: true
doc-warnings: false

ignore-paths:
  - docs

ignore-patterns:
  - ^__init__.py$

pycodestyle:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 79

Bandit:
  run: false

pylint:
  run: false

frosted:
  run: false

mypy:
  run: false

pep257:
  run: false

pep8:
  run: false

pyroma:
  run: false

vulture:
  run: false
